apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: trinity
data:
  alerting-rules.yml: |
    groups:
    - name: aki-alerts
      rules:
      - alert: PageFailed
        expr: increase(pages_failed_total[1m]) > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "page failed"
          description: "Page failed (> 1 in the last minute)."
