apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: trinity
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
