apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: trinity
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'aki-detection'
        static_configs:
          - targets: ['aki-detection-service.trinity.svc.cluster.local:8000']
        metrics_path: '/metrics'
    rule_files:
      - "/etc/prometheus/rules/alerting-rules.yml"
    alerting:
        alertmanagers:
        - static_configs:
          - targets:
            - 'alertmanager.trinity.svc.cluster.local:9093'
